spring:
  jpa:
    hibernate:
      ddl-auto: update

datasource:
  master:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/string_portal
    username: root
    password: mariadb
    connection-test-query: SELECT main 1
    maximum-pool-size: 8
  slave:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/string_portal
    username: root
    password: mariadb
    connection-test-query: SELECT sub 1
    maximum-pool-size: 8

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    jdbc.resultsettable : info
    jdbc.sqlonly: info
    org.springframework.web: ERROR
  config: classpath:logback-dev.xml

jwt:
  secret: stringportal*dev#secret
  access:
    name: access